version: 2
updates:
  - package-ecosystem: gomod
    directory: /apps/api
    schedule:
      interval: weekly
    groups:
      go:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ['*']
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directories:
      - /apps/api
      - /apps/web
    schedule:
      interval: weekly
